### Salaries Dataset Cleaning and Aggregation

##### This notebooks highlights case study analysis on salaries dataset gathered from Kaggle, and will be used to highlight:
- Data Ingestion from SQLite
- Data Cleaning Techniques
- Data Aggregations and Pivot Tables
- Exploratory Data Analysis (EDA)

### Data Ingestion using SQLAlchemy

In [1]:
# import necessary libraries
from sqlalchemy import create_engine, text
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
# load the database file using function
def load_db(eng: str, query: str) -> pd.DataFrame:

    with eng.connect() as conn:
        return pd.read_sql_query(query, conn)

In [3]:
# load data
engine = create_engine("sqlite:///../data/raw/database.sqlite")
df = load_db(engine, "SELECT * FROM Salaries")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [4]:
# inspect data
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148654 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          148654 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             148654 non-null  object
 11  Agency            148654 non-null  object
 12  Status            148654 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 14.7+ MB

Id                  0
EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
Notes               0
Agency              0
Status              0
dtype: int64

In [5]:
df.describe()

                  Id       TotalPay  TotalPayBenefits           Year
count  148654.000000  148654.000000     148654.000000  148654.000000
mean    74327.500000   74768.321972      93692.554811    2012.522643
std     42912.857795   50517.005274      62793.533483       1.117538
min         1.000000    -618.130000       -618.130000    2011.000000
25%     37164.250000   36168.995000      44065.650000    2012.000000
50%     74327.500000   71426.610000      92404.090000    2013.000000
75%    111490.750000  105839.135000     132876.450000    2014.000000
max    148654.000000  567595.430000     567595.430000    2014.000000

### Cleaning Pipeline

In [6]:
# standardize columns

# remove the id column
df = df.drop(columns=['Id'])
headers = [
    "employee_name", "job_title", "base_pay", "overtime_pay", 
    "other_pay", "benefits", "total_pay", "total_pay_benefits", 
    "year", "notes", "agency", "status" 
]
df.columns = headers
df

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,notes,agency,status
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [7]:
import re
# standardize employee names to title
df["employee_name"] = df["employee_name"].apply(lambda s: s.title())

# standardize job_title col
df["job_title"] = df["job_title"].apply(lambda j: j.title())

roman_map = ['I', 'Ii', 'Iii', 'Iv', 'Vi', 'Vii', 'Viii', 'Ix', 'X', "Xiv", "Xvii", "Xvi", "Xviii", "Xv"]
pattern = r'\b(' + '|'.join(roman_map) + r')\b'

df['job_title'] = df['job_title'].str.replace(
    pattern, 
    lambda m: m.group(0).upper(), 
    regex=True
)

In [8]:
df["job_title"].value_counts()

job_title
Transit Operator                  9424
Special Nurse                     5791
Registered Nurse                  4955
Custodian                         3214
Firefighter                       3153
                                  ...
Captain, (Fire Department)           1
Sr Cnselor, Juv Hall (Sfers)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 1637, dtype: int64

In [9]:
# for the base pay
df["base_pay"].value_counts()

df["base_pay"] = (
    df["base_pay"]
    .astype(str)
    .replace("", 0)
    .str.strip()
)

df["overtime_pay"] = (
    df["overtime_pay"]
    .astype(str)
    .replace("", 0)
    .str.strip()
)

df["other_pay"] = (
    df["overtime_pay"]
    .astype(str)
    .replace("", 0)
    .str.strip()
)

df["benefits"] = (
    df["benefits"]
    .astype(str)
    .replace("", 0)
    .str.strip()
)

df["base_pay"] = pd.to_numeric(df["base_pay"], errors='coerce')
df["overtime_pay"] = pd.to_numeric(df["overtime_pay"], errors='coerce')
df["other_pay"] = pd.to_numeric(df["overtime_pay"], errors='coerce')
df["benefits"] = pd.to_numeric(df["benefits"], errors='coerce')


# I was thinking if to drop both columns with unprovided job title and 0 base pay (so I did.)
df = df[(df["job_title"] != "Not Provided") & (df["base_pay"] != 0)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147352 entries, 0 to 148620
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   employee_name       147352 non-null  object
 1   job_title           147352 non-null  object
 2   base_pay            146747 non-null  float64
 3   overtime_pay        147352 non-null  float64
 4   other_pay           147352 non-null  float64
 5   benefits            111645 non-null  float64
 6   total_pay           147352 non-null  float64
 7   total_pay_benefits  147352 non-null  float64
 8   year                147352 non-null  int64
 9   notes               147352 non-null  object
 10  agency              147352 non-null  object
 11  status              147352 non-null  object
dtypes: float64(6), int64(1), object(5)
memory usage: 14.6+ MB

In [10]:
negatives = df[df['total_pay_benefits'] < 0]
negatives

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,notes,agency,status
110528,Timothy E Gibson,Police Officer 3,NaN,0.0,0.0,-2.73,0.0,-2.73,2013,,San Francisco,
110529,Mark E Laherty,Police Officer 3,NaN,0.0,0.0,-8.20,0.0,-8.20,2013,,San Francisco,
110530,David P Kucia,Police Officer 3,NaN,0.0,0.0,-33.89,0.0,-33.89,2013,,San Francisco,